### ISSUE TITLE
Power Park appears twice in list

### ISSUE THREAD

**Issue by Wuzzy2** [PFCKrutonium/OpenRCT2-OpenScenarios#12]
There are 2 scenarios with the same name “Power Park”. One is a giant park with tons of attractions while the other one is a sandbox scenario. This creates ambiguity.

I suggest to rename one of the scenarios/parks to disambiguate them.

**Comment by Gymnasiast** [comment]
Many parks need a bit of curating anyway. But since the collection is nowhere near complete (no expert parks or real parks), we are first collecting all the parks we get and then make a selection from it, fix the names, descriptions, etc.

**Comment by 733737** [comment]
This issue would be fixed by my merge request
