### ISSUE TITLE
Gentleman's Garden

### ISSUE THREAD

**Issue by Xedoh** [PFCKrutonium/OpenRCT2-OpenScenarios#8]
[Gentleman's Garden.zip](https://github.com/PFCKrutonium/OpenRCT2-OpenScenarios/files/1335243/Gentleman.s.Garden.zip)
I'd like some opinions on the description of the scenario: is it clear enought that guests prefer low-intensitiy rides?

**Comment by Krutonium** [comment]
>Build a park for those who prefer a less intense experience in this beautiful garden.

I'd say so, yeah
